In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pso_from_scratch as pfs
import importlib


In [2]:
importlib.reload(pfs)

<module 'pso_from_scratch' from '/home/wildfire/Computational-intelligence-in-data-analysis/Lab1/pso_from_scratch.py'>

In [3]:
def Rozenbrock(x):
    '''Test function for PSO - banana function Rozenbrock'''

    return (1 - x[0])**2 + 100*(x[1] - x[0]**2)**2
    

In [4]:
test = pfs.pso(spawn_x = -10, spawn_y = 10)
print(test.social_tendency)

None


In [5]:
spawn = test.create_population(2, 16)
spawn

array([[ 4.82448167, -3.98689689],
       [ 6.75414433,  7.18399523],
       [-9.64659162, -7.68834417],
       [ 3.14489856, -7.54569103],
       [-8.304369  , -2.59579958],
       [-5.44668973, -4.70405739],
       [ 9.4723287 ,  4.8944762 ],
       [-0.26354358, -6.72377359],
       [-6.50763946,  0.6060411 ],
       [ 7.19300118,  3.66730768],
       [ 0.26356884,  8.41998891],
       [-9.38884898,  1.64570932],
       [-3.18516249,  5.67848765],
       [-8.68775568, -7.42202101],
       [ 1.52224595,  9.88904476],
       [ 0.93749428, -4.65517985]])

In [6]:
best_pop, best_val = test.pso_engine(Rozenbrock, 2, 16, 600)

In [7]:
best_pop

array([0.99999612, 0.99999247])

In [8]:
best_val

1.997473688560842e-11

In [9]:
x = np.array([[ -2.14825586,  -0.8661696 ],
       [ -0.0554764 , -12.11070838],
       [  0.2584984 ,   0.17145921],
       [  0.        ,   0.        ],
       [  0.36661794,  -8.86352358],
       [  1.13991162,  -0.08297975],
       [ -8.08288526,   0.13305724],
       [  2.62894195,  -1.74992444],
       [ 11.37185222,  -5.61157875],
       [  0.42912651,  -6.67058097],
       [ -3.58657577, -14.47113024],
       [  2.88197048,  -0.92660694],
       [  8.08584674,   2.70748008],
       [  9.04856139,  -5.14627017],
       [  1.79764147,   3.04536995],
       [ -0.58336598,  -0.45288752]])
x[4]

array([ 0.36661794, -8.86352358])